name: Archived Fashion
version: 1.0.0
author: Your Name
summary: A retro-futuristic Japanese fashion archive theme
description: A unique theme that combines retro arcade aesthetics with Japanese fashion archives, featuring neon accents, scanline effects, and bilingual support.
documentation: https://github.com/yourusername/archived-fashion
support: https://github.com/yourusername/archived-fashion/issues 